In [2]:
import pandas as pd 
import numpy as np
from sklearn.metrics import log_loss

In [3]:
df=pd.read_csv('data/train.csv')
df.head()

Id        AB          AF          AH         AM        AR  \
0  000ff2bfdfe9  0.209377  3109.03329   85.200147  22.394407  8.138688   
1  007255e47698  0.145282   978.76416   85.200147  36.968889  8.138688   
2  013f2bd269f5  0.470030  2635.10654   85.200147  32.360553  8.138688   
3  043ac50845d5  0.252107  3819.65177  120.201618  77.112203  8.138688   
4  044fb8a146ec  0.380297  3733.04844   85.200147  14.103738  8.138688   

         AX        AY         AZ          BC  ...        FL        FR  \
0  0.699861  0.025578   9.812214    5.555634  ...  7.298162   1.73855   
1  3.632190  0.025578  13.517790    1.229900  ...  0.173229   0.49706   
2  6.732840  0.025578  12.824570    1.229900  ...  7.709560   0.97556   
3  3.685344  0.025578  11.053708    1.229900  ...  6.122162   0.49706   
4  3.942255  0.054810   3.396778  102.151980  ...  8.153058  48.50134   

         FS         GB          GE            GF         GH         GI  \
0  0.094822  11.339138   72.611063   2003.810319  22.136229  69.834944   
1  0.568932   9.292698   72.611063  27981.562750  29.135430  32.131996   
2  1.198821  37.077772   88.609437  13676.957810  28.022851  35.192676   
3  0.284466  18.529584   82.416803   2094.262452  39.948656  90.493248   
4  0.121914  16.408728  146.109943   8524.370502  45.381316  36.262628   

          GL  Class  
0   0.120343      1  
1  21.978000      0  
2   0.196941      0  
3   0.155829      0  
4   0.096614      1  

[5 rows x 58 columns]

In [4]:
plot_df = df.Class.value_counts()
plot_df

0    509
1    108
Name: Class, dtype: int64

Class 1 - Has one or many of three conditions (108)
Class 0 - None of the three medical conditions(509)

In [5]:
#dropping ID column as it will not be used 
#also drop the predictor 

train_data=df.drop(columns=['Id','Class'])
train_data.head()

AB          AF          AH         AM        AR        AX        AY  \
0  0.209377  3109.03329   85.200147  22.394407  8.138688  0.699861  0.025578   
1  0.145282   978.76416   85.200147  36.968889  8.138688  3.632190  0.025578   
2  0.470030  2635.10654   85.200147  32.360553  8.138688  6.732840  0.025578   
3  0.252107  3819.65177  120.201618  77.112203  8.138688  3.685344  0.025578   
4  0.380297  3733.04844   85.200147  14.103738  8.138688  3.942255  0.054810   

          AZ          BC         BD   ...         FI        FL        FR  \
0   9.812214    5.555634  4126.58731  ...   3.583450  7.298162   1.73855   
1  13.517790    1.229900  5496.92824  ...  10.358927  0.173229   0.49706   
2  12.824570    1.229900  5135.78024  ...  11.626917  7.709560   0.97556   
3  11.053708    1.229900  4169.67738  ...  14.852022  6.122162   0.49706   
4   3.396778  102.151980  5728.73412  ...  13.666727  8.153058  48.50134   

         FS         GB          GE            GF         GH         GI  \
0  0.094822  11.339138   72.611063   2003.810319  22.136229  69.834944   
1  0.568932   9.292698   72.611063  27981.562750  29.135430  32.131996   
2  1.198821  37.077772   88.609437  13676.957810  28.022851  35.192676   
3  0.284466  18.529584   82.416803   2094.262452  39.948656  90.493248   
4  0.121914  16.408728  146.109943   8524.370502  45.381316  36.262628   

          GL  
0   0.120343  
1  21.978000  
2   0.196941  
3   0.155829  
4   0.096614  

[5 rows x 56 columns]

In [6]:
X=train_data
X

AB          AF          AH          AM         AR        AX  \
0    0.209377  3109.03329   85.200147   22.394407   8.138688  0.699861   
1    0.145282   978.76416   85.200147   36.968889   8.138688  3.632190   
2    0.470030  2635.10654   85.200147   32.360553   8.138688  6.732840   
3    0.252107  3819.65177  120.201618   77.112203   8.138688  3.685344   
4    0.380297  3733.04844   85.200147   14.103738   8.138688  3.942255   
..        ...         ...         ...         ...        ...       ...   
612  0.149555  3130.05946  123.763599    9.513984  13.020852  3.499305   
613  0.435846  5462.03438   85.200147   46.551007  15.973224  5.979825   
614  0.427300  2459.10720  130.138587   55.355778  10.005552  8.070549   
615  0.363205  1263.53524   85.200147   23.685856   8.138688  7.981959   
616  0.482849  2672.53426  546.663930  112.006102   8.138688  3.198099   

           AY         AZ          BC         BD   ...         FI         FL  \
0    0.025578   9.812214    5.555634  4126.58731  ...   3.583450   7.298162   
1    0.025578  13.517790    1.229900  5496.92824  ...  10.358927   0.173229   
2    0.025578  12.824570    1.229900  5135.78024  ...  11.626917   7.709560   
3    0.025578  11.053708    1.229900  4169.67738  ...  14.852022   6.122162   
4    0.054810   3.396778  102.151980  5728.73412  ...  13.666727   8.153058   
..        ...        ...         ...         ...  ...        ...        ...   
612  0.077343   8.545512    2.804172  4157.68439  ...   9.879296   0.173229   
613  0.025882  12.622906    3.777550  5654.07556  ...  10.910227  10.223150   
614  0.025578  15.408390    1.229900  5888.87769  ...  12.029366   0.173229   
615  0.025578   7.524588    1.229900  4517.86560  ...   8.026928   9.256996   
616  0.116928   3.396778    7.948668  2818.01707  ...   7.745765   0.173229   

           FR        FS         GB          GE            GF         GH  \
0     1.73855  0.094822  11.339138   72.611063   2003.810319  22.136229   
1     0.49706  0.568932   9.292698   72.611063  27981.562750  29.135430   
2     0.97556  1.198821  37.077772   88.609437  13676.957810  28.022851   
3     0.49706  0.284466  18.529584   82.416803   2094.262452  39.948656   
4    48.50134  0.121914  16.408728  146.109943   8524.370502  45.381316   
..        ...       ...        ...         ...           ...        ...   
612   1.26092  0.067730   8.967128  217.148554   8095.932828  24.640462   
613   1.24236  0.426699  35.896418  496.994214   3085.308063  29.648928   
614   0.49706  0.067730  19.962092  128.896894   6474.652866  26.166072   
615   0.78764  0.670527  24.594488   72.611063   1965.343176  25.116750   
616   1.14492  0.149006  13.673940   72.611063   6850.484442  45.745974   

             GI         GL  
0     69.834944   0.120343  
1     32.131996  21.978000  
2     35.192676   0.196941  
3     90.493248   0.155829  
4     36.262628   0.096614  
..          ...        ...  
612   69.191944  21.978000  
613  124.808872   0.145340  
614  119.559420  21.978000  
615   37.155112   0.184622  
616  114.842372  21.978000  

[617 rows x 56 columns]

In [7]:
#The predictor
y=df['Class']



# Building a naive model

 The naive model would be that every patient has a 17.5% probability to have one of the three age related conditions. We will need to compute the balanced log loss for the naive model and use it as the baseline balanced log loss. Any other models that we make should have a balanced log loss that is less than that of our naive model.

In [8]:
class_zero=509 #frequency of class zero
class_one=108 #frequency of class one 
both=class_zero+class_one
prob_of_one=class_one/(class_one+class_zero)
prob_of_one_percentage=(class_one/(class_one+class_zero))*100
prob_of_one_percentage

17.504051863857377

In [9]:
prob_of_zero=class_zero/(class_one+class_zero)
prob_of_zero_percentage=(class_zero/(class_one+class_zero))*100
prob_of_zero_percentage

82.49594813614263

In [10]:
 #This means we create an array of length freq_class_0 + freq_class_1 where each element is prob_class_1 .
y_pred = np.array([prob_of_one] * both)
y_pred

array([0.17504052, 0.17504052, 0.17504052, 0.17504052, 0.17504052,
       0.17504052, 0.17504052, 0.17504052, 0.17504052, 0.17504052,
       0.17504052, 0.17504052, 0.17504052, 0.17504052, 0.17504052,
       0.17504052, 0.17504052, 0.17504052, 0.17504052, 0.17504052,
       0.17504052, 0.17504052, 0.17504052, 0.17504052, 0.17504052,
       0.17504052, 0.17504052, 0.17504052, 0.17504052, 0.17504052,
       0.17504052, 0.17504052, 0.17504052, 0.17504052, 0.17504052,
       0.17504052, 0.17504052, 0.17504052, 0.17504052, 0.17504052,
       0.17504052, 0.17504052, 0.17504052, 0.17504052, 0.17504052,
       0.17504052, 0.17504052, 0.17504052, 0.17504052, 0.17504052,
       0.17504052, 0.17504052, 0.17504052, 0.17504052, 0.17504052,
       0.17504052, 0.17504052, 0.17504052, 0.17504052, 0.17504052,
       0.17504052, 0.17504052, 0.17504052, 0.17504052, 0.17504052,
       0.17504052, 0.17504052, 0.17504052, 0.17504052, 0.17504052,
       0.17504052, 0.17504052, 0.17504052, 0.17504052, 0.17504

In [57]:
#we are basically predicting class zero all the time 
y_pred_classes = np.array([0] * both)
y_pred_classes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [11]:
y_true = np.array([0] * class_zero + [1] * class_one)
y_true

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [12]:
#normal log_loss
normal_log_loss=log_loss(y_true,y_pred)
normal_log_loss

0.46378926223013367

In [66]:
#balanced log loss formula
def b_log_loss(y_t, y_p):
    nc = np.bincount(y_true)
    sample_weight = 1 / nc[y_true]
    return log_loss(y_t, y_p, sample_weight=sample_weight, eps=1e-15)

In [35]:
#balanced log loss 
balanced_log_loss= b_log_loss(y_true, y_pred)
balanced_log_loss

0.9675794020680167

# Preprocessing pipelines 

Only one column `EJ` is categorical. We will separate them and apply prepprocessing piplines to both.

In [15]:
train_data['EJ'].isna().sum()

0

In [16]:
from sklearn.preprocessing import FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

#numerical pipeline

imputer=SimpleImputer(strategy='median')
log_transformer=FunctionTransformer(np.log1p, inverse_func=np.expm1)
scaler=StandardScaler()

numerical_pipeline=Pipeline([
    ('impute',imputer),
    ('log transform',log_transformer),
    ('scale', scaler)
])

In [17]:
#categorical pipeline 

from sklearn.preprocessing import OneHotEncoder

cat_encoder=OneHotEncoder()
cat_pipeline=Pipeline([
    ('encoder',cat_encoder)
])

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.compose import make_column_selector


X_preprocessing=ColumnTransformer([
    ('numerical', numerical_pipeline,make_column_selector(dtype_include=np.number)),
    ('categorical',cat_pipeline, make_column_selector(dtype_include=object) )
])

# Modelling

The data is not much so we will use k-fold  cross validation. We will make use of the pipeline to avoid data leakage.

In [19]:
#logistic regression

from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression(fit_intercept=False, C=1e12, solver='liblinear', class_weight='balanced')


In [20]:
#logistic regression training pipeline 

logreg_pipeline= Pipeline([
    ('preprocess', X_preprocessing),
    ('classifier',logreg)
])

In [74]:
#cross-validation strategy

from sklearn.model_selection import cross_val_score, cross_val_predict, KFold
cv=KFold(n_splits=5, shuffle=True, random_state=42)


In [75]:
processsed=X_preprocessing.fit_transform(X)
model=logreg.fit(processsed,y)
predicted_probs=model.predict_proba(processsed)
balanced_log_loss= b_log_loss(y_true, predicted_probs)
print(balanced_log_loss)

2.6857491089938375


In [22]:
#other metrics: precision, accuracy, recall
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score

predicted_labels = cross_val_predict(logreg_pipeline, X, y, cv=cv)
accuracy = accuracy_score(y, predicted_labels)
precision = precision_score(y, predicted_labels, average='macro')
recall = recall_score(y, predicted_labels, average='macro')
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)

Accuracy: 0.8881685575364667
Precision: 0.8003345498783455
Recall: 0.8592738121225351


In [23]:
from sklearn.tree import DecisionTreeClassifier 
dt= DecisionTreeClassifier(random_state=42)

In [24]:
dt_pipeline=Pipeline([
    ('preprocessing', X_preprocessing),
    ('model',dt)
    
] 
)

In [25]:
predicted_labels = cross_val_predict(dt_pipeline, X, y, cv=cv)
accuracy = accuracy_score(y, predicted_labels)
precision = precision_score(y, predicted_labels, average='macro')
recall = recall_score(y, predicted_labels, average='macro')
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)

Accuracy: 0.8833063209076175
Precision: 0.7973014165321858
Recall: 0.8016171869315287


In [69]:
processsed=X_preprocessing.fit_transform(X)
model=dt.fit(processsed,y)
predicted_probs=model.predict_proba(processsed)
balanced_log_loss= b_log_loss(y_true, predicted_probs)
print(balanced_log_loss)

17.250853417864832


In [43]:
from sklearn.neighbors import KNeighborsClassifier 
knn=KNeighborsClassifier() 

In [44]:
knn_pipeline=Pipeline([
    ('preprocessing', X_preprocessing),
    ('model',knn)
])

In [70]:
processsed=X_preprocessing.fit_transform(X)
model=knn.fit(processsed,y)
predicted_probs=model.predict_proba(processsed)
balanced_log_loss= b_log_loss(y_true, predicted_probs)
print(balanced_log_loss)

13.09901462077517


In [ ]:
predicted_labels = cross_val_predict(knn_pipeline, X, y, cv=cv)
accuracy = accuracy_score(y, predicted_labels)
precision = precision_score(y, predicted_labels, average='macro')
recall = recall_score(y, predicted_labels, average='macro')
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)

Accuracy: 0.899513776337115
Precision: 0.8868352223190933
Recall: 0.7421414538310412


In [46]:
#remember we cannot use rf and xgboost but we can uae them to compare with the dinal model we come up with 
from sklearn.ensemble import RandomForestClassifier 
rf=RandomForestClassifier(random_state=42)

In [47]:
rf_pipeline=Pipeline([
    ('preprocessing',X_preprocessing),
    ('model',rf)
])

In [71]:
processsed=X_preprocessing.fit_transform(X)
model=rf.fit(processsed,y)
predicted_probs=model.predict_proba(processsed)
balanced_log_loss= b_log_loss(y_true, predicted_probs)
print(balanced_log_loss)

3.6589696494581894


In [ ]:
predicted_labels = cross_val_predict(rf_pipeline, X, y, cv=cv)
accuracy = accuracy_score(y, predicted_labels)
precision = precision_score(y, predicted_labels, average='macro')
recall = recall_score(y, predicted_labels, average='macro')
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)

Accuracy: 0.9189627228525121
Precision: 0.9072719127967747
Recall: 0.7976970093865968


In [50]:
#xgboost#check log loss, hence balanced log loss 
from sklearn.ensemble import GradientBoostingClassifier
xg_boost=GradientBoostingClassifier(random_state=42)


In [51]:
xg_pipeline=Pipeline([
    ('preprocessing',X_preprocessing),
    ('model',xg_boost)
])

In [77]:
processsed=X_preprocessing.fit_transform(X)
model=xg_boost.fit(processsed,y)
predicted_probs=model.predict_proba(processsed)
balanced_log_loss= b_log_loss(y_true, predicted_probs)
print(balanced_log_loss)

2.321568102315544


In [ ]:
predicted_labels = cross_val_predict(xg_pipeline, X, y, cv=cv)
accuracy = accuracy_score(y, predicted_labels)
precision = precision_score(y, predicted_labels, average='macro')
recall = recall_score(y, predicted_labels, average='macro')
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)

Accuracy: 0.9222042139384117
Precision: 0.8799377568040356
Recall: 0.8397820708724442


In [ ]:
#using SMOTE 
